### ISSUE TITLE
Delete Terminal Not Working with Tornado version 6.0.1

### ISSUE THREAD

**Issue by cpranav** [jupyter/terminado#62]
Delete Terminal call is throwing 500 from Jupyter Server. Below is the stacktrace,

```
[E 21:50:25.879 NotebookApp] Uncaught exception DELETE /api/terminals/1 (10.0.1.74)
    HTTPServerRequest(protocol='https', host='10.0.94.86:8443', method='DELETE', uri='/api/terminals/1', version='HTTP/1.1', remote_ip='10.0.1.74')
    Traceback (most recent call last):
      File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/tornado/web.py", line 1699, in _execute
        result = await result
      File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/tornado/gen.py", line 736, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/notebook/terminal/api_handlers.py",line 36, in delete
        yield tm.terminate(name, force=True)
      File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/tornado/gen.py", line 729, in run
        value = future.result()
      File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/tornado/gen.py", line 736, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/terminado/management.py", line 333,in terminate
        yield term.terminate(force=force)
      File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/tornado/gen.py", line 729, in run
        value = future.result()
      File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/tornado/gen.py", line 209, in wrapper
        yielded = next(result)
      File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/terminado/management.py", line 96, in terminate
        yield sleep()
      File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/terminado/management.py", line 89, in <lambda>
        sleep = lambda : gen.Task(loop.add_timeout, loop.time() + self.ptyproc.delayafterterminate)
    AttributeError: module 'tornado.gen' has no attribute 'Task'
[W 21:50:26.118 NotebookApp] Unhandled error
[E 21:50:26.118 NotebookApp] {
```

After browsing through Jupyter issues directory I could find similar issue with Tornado related to Jupyter and was addressed in  https://github.com/jupyter/notebook/issues/4439 though it doesn't address Terminal issue. PR for the Jupyter fix for reference, https://github.com/jupyter/notebook/commit/d17caf92c0817e8bc771209a1e867f0c73e34724

I think we need to make a similar fix in 
https://github.com/jupyter/terminado/blob/master/terminado/management.py#L89

**Comment by cpranav** [comment]
Thanks @takluyver . Do you know when would be the new version of terminado plan to be release which would pick up the fix for this bug?

**Comment by blink1073** [comment]
0.8.2 is released with the fix.
